### ISSUE TITLE
Do not host all versions of the spec on the website

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-website#2]
Instead of hosting all versions of the spec on the website, why not simply point people to reuse-docs for prior versions of the spec? This simplifies the building of the website, and people who want prior versions of the spe probably won't be annoyed at having to dig a little deeper into a code repo.

**Comment by mxmehl** [comment]
Yes, makes sense. But we should indicate the current version number somewhere on this page

**Comment by mxmehl** [comment]
Will be closed as soon as we will use v3.0 of reuse-docs
