### ISSUE TITLE
make this website translatable

### ISSUE THREAD

**Issue by eighthave** [fsfe/reuse-website#26]
@uniqx and I are currently working on improving translation workflows for Markdown using all free software (_po4a_ and Weblate).  We'd like to submit a pull request to make this site translatable using this workflow, and then submit it to free hosting on hosted.weblate.org.

This means:
* Breaking out the menu from _site/config.toml_ to per-language files.
* Adding _po4a.conf_ for managing the conversion to _gettext_ PO format.
* Maintaining a _po/_ dir for the .po and .pot files which Weblate will work with.
* Adding a website pre-build step that makes _po4a_ generate all the translated .md files

Is this something that you would accept?

**Comment by carmenbianca** [comment]
Hey, that's awesome! I'll ping @mxmehl on this, but from my end, I'd love to have the website be translateable.

I know that @mxmehl made https://publiccode.eu/ (https://git.fsfe.org/pmpc/website) translateable using just Hugo. But I don't think that Markdown was used for that website.

One important detail for this project is that---kind of sort of---content and Hugo stuff is separated between https://github.com/fsfe/reuse-docs and https://fsfe/reuse-website. That might complicate things.

**Comment by mxmehl** [comment]
Thanks for the offer @eighthave @uniqx!

> I know that @mxmehl made https://publiccode.eu/ (https://git.fsfe.org/pmpc/website) translateable using just Hugo. But I don't think that Markdown was used for that website.

The PMPC website uses strings (in i18n) and markdown files (in content/), so all that Hugo provided at this point ;)

> One important detail for this project is that---kind of sort of---content and Hugo stuff is separated between https://github.com/fsfe/reuse-docs and https://fsfe/reuse-website. That might complicate things.

That, and I was a bit hesitant towards translations when creating the website because I am afraid of outdated information. Especially with the spec/tutorial/FAQ, but also for instructions for developers (that may change with new tool or API versions) and so on.

In the area of development and license compliance, English is so widely understood that I am not sure whether the benefits (translations are great, wider audience, ease adoptions for everyone) would outweigh the downsides (outdated information, only partly translations).

Just my 2 cents for now, happy for more input!

**Comment by eighthave** [comment]
Using the po4a workflow, it is possible to only publish translated pages
that are 100% current.  So that means any change to the source page
would cause translated pages to automatically switch to English if they
are not 100% current when the website is rebuilt.

I think in the German speaking world, people are happy to do technical
work in English.  My experience in the Spanish- and French-speaking
world is that people who speak English will still prefer to work in
their own language.

**Comment by mxmehl** [comment]
> Using the po4a workflow, it is possible to only publish translated pages that are 100% current

Sounds like what we need!

I am happy to explore this workflow, given that the extra complexity due to the split between reuse-website and reuse-docs will not be too high.

**Comment by eighthave** [comment]
#29 and https://github.com/fsfe/reuse-docs/pull/61 are the first key steps towards localizing this site.  Those need to happen regardless of how things are integrated into the translation workflow, so I've done those first.  Then we can separately figure out the exact integration and workflow with Weblate.

**Comment by eighthave** [comment]
Pull request #29 has been waiting for review since May 4th.  It should be easy to review, it just makes things be more standard Hugo style, which makes it a lot easier to localize.  Once that is merged, I'll follow up with the actual full localization pull request, which I have locally implemented.

**Comment by mxmehl** [comment]
Sorry for the long wait, we had to wrap our heads around localisation first and how to deal with differing interpretations. Will follow up on the two PRs individually.

Is there a standard possibility to add some kind of warning text above translations on specific pages? So for instance, it'd be important that on top of `spec.md` people are aware that the English version is binding, and translations are inofficial. I could think of some Hugo shortcut displaying some translatable text on non-EN pages, but wanted to ask first for best practices.

**Comment by eighthave** [comment]
Its surely possible.  I haven't seen this specific thing implemented
before, but I haven't really surveyed websites for such things either.
I think it makes sense to handle it in the Hugo template.  It should be
straightforward to add a check whether the page is being rendered in the
default language, and if not, post a message.  That message should be
available for translation though.
