### ISSUE TITLE
license information claims logos for Huawei, Siemens and others are (C) FSFE

### ISSUE THREAD

**Issue by aburch** [fsfe/reuse-website#51]
I ran "reuse spdx" on the website repository (commit 09951650599d7fa77147213d9b21362ba28243ff) and among others it reported:

```
FileName: ./site/static/img/organisations/huawei.png
SPDXID: SPDXRef-7bd68e2cfea7e7f44a6aab23757ccd3f
FileChecksum: SHA1: 41a9e5bd8d858eb86f815380d75ce020b0655cfd
LicenseConcluded: NOASSERTION
LicenseInfoInFile: CC-BY-SA-4.0
FileCopyrightText: <text>2019 Free Software Foundation Europe <https://fsfe.org></text>
```

I doubt that the FSFE holds copyright for this file and suspect license and copyright information are too unspecific at some place (probably a bug in the website?)

The Siemens logo has a separate `.license` file and was reported as:

```
FileName: ./site/static/img/organisations/gray/siemens.png
SPDXID: SPDXRef-1772acb13a58458f96e8bc5860eed12b
FileChecksum: SHA1: 59f1cda9e68a617086d6eb6e248c5de5cf1d5acd
LicenseConcluded: NOASSERTION
LicenseInfoInFile: CC-BY-SA-4.0
LicenseInfoInFile: CC0-1.0
FileCopyrightText: <text>2019 Free Software Foundation Europe <https://fsfe.org>
SPDX-FileCopyrightText: Siemens AG</text>
```

I guess this might be a bug in the `reuse` tool?

(I used reuse 1.0.0-1 from Debian testing/unstable.)

**Comment by mxmehl** [comment]
Thank you, that should have been fixed with commit 3004411eb34cf8bfff20d7ce0473b73abf16406d
