### ISSUE TITLE
FSFE logo is missing

### ISSUE THREAD

**Issue by mxmehl** [fsfe/reuse-website#61]
#57 seems to be incomplete, the referenced logo file is missing:

![image](https://github.com/fsfe/reuse-website/assets/6170081/34ec542f-1a3f-428b-8be9-97f4b04ae411)

**Comment by xplosionmind** [comment]
I was about to open the same issue, but happy to acknowledge the problem was reported already!

Apparently, I spot some sort of network failure while downloading the resource:

![image](https://github.com/fsfe/reuse-website/assets/42862428/8b2cba92-58fc-4917-a711-2a9f57519405)
