### ISSUE TITLE
Links to SPDX 2.1 are 404

### ISSUE THREAD

**Issue by BigBlueHat** [fsfe/reuse-website#62]
There are several throughout the site, but they're most notable on the [specification page](https://reuse.software/spec/).

This is a typical example of the link:
https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60

This is certainly an upstream problem--as even [SPDX's own links](https://spdx.dev/use/specifications/) to the v2.1 spec are 404...

However, SPDX is now at v2.3, so perhaps finding updated equivalence would be best.

**Comment by mxmehl** [comment]
That should all be fixed when we release 3.2 of the spec: https://github.com/fsfe/reuse-docs/pull/133

So I'd close this as duplicate as it's fixed in the dev branch of the spec already. Thanks for reporting it anyway!
