### ISSUE TITLE
Following guidance in /dev/ breaks reuse compliance

### ISSUE THREAD

**Issue by chrysn** [fsfe/reuse-website#94]
I have a project that I want to have reuse checked, and being hosted on GitHub, actions are nice checking.

So I went to https://reuse.software/dev/#github and followed the steps for adding the Action: created `.github/workflows/reuse.yaml` and copy-pasted the text below in there.

Boom:

```
The following files have no copyright and licensing information:
* .github/workflows/reuse.yaml
[...]
Unfortunately, your project is not compliant with version 3.2 of the REUSE Specification :-(
```

That snippet may not even pass the threshold of originality, but a) it's common practice in FLOSS to just assume everything does, and b) REUSE does not differentiate.

Could you state which license applies, whom to put as the copyright holder (a somewhat moot thing if the license is CC0-1.0 which I assume would fit), and place that into a top comment in the snippet? Then copying it in would *still* break reuse unless that license is already in there, but at least the fix is just a `reuse download` away, and doesn't need more information.

**Comment by carmenbianca** [comment]
Thanks! I've fixed this in 5a870f6 by adding a CC0 license to the snippets. You're right in assuming that CC0 would have sufficed.
